In [42]:
# importing all required libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import numpy as np

In [43]:
x = np.array([[0,0], [0,1], [1,0],[1,1]], "uint8") # input array of an AND gate
y = np.array([[0], [0], [0], [1]], "uint8") #output array

In [44]:
AND_model = Sequential()
AND_model.add(Dense(units=1, activation='sigmoid', input_dim=2)) #create output layer with 1 neuron 
AND_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
AND_model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
AND_model.fit(x, y, epochs=5000) # train an AND model

In [46]:
print(AND_model.layers[0].get_weights())

[array([[2.4313061],
       [2.9032228]], dtype=float32), array([-4.1607127], dtype=float32)]


In [47]:
AND_model.predict(x) # prdicted output of an AND model

array([[0.01535696],
       [0.22140631],
       [0.1506635 ],
       [0.7638341 ]], dtype=float32)

In [48]:
x = [[0,0], [0,1], [1,0], [1,1]] #input array of a XOR model
y = [[0], [1], [1], [0]]# output array

In [49]:
XOR_model =Sequential()
XOR_model.add(Dense(2, input_dim=2, activation='sigmoid')) # output layer with 2 neron
XOR_model.add(Dense(1, activation='sigmoid')) #output layer with 1 neron
XOR_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
XOR_model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 2)                 6         
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
XOR_model.fit(x, y, epochs=3000) # train XOR model

In [55]:
XOR_model.get_weights()

[array([[ 5.9076285,  6.69145  ],
        [-6.695324 , -6.2683043]], dtype=float32),
 array([-3.249003 ,  3.3246148], dtype=float32),
 array([[ 6.6885815],
        [-6.214812 ]], dtype=float32),
 array([2.986019], dtype=float32)]

In [56]:
XOR_model.predict(x)# predicted output of XOR model

array([[0.05935606],
       [0.935558  ],
       [0.9535686 ],
       [0.04881659]], dtype=float32)